name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - uses: gradle/actions/setup-gradle@v4 # v4.0.0

      - name: Publish to GitHub Packages
        run: ./gradlew publish -Prelease.useLastTag=true
        env:
          ORG_GRADLE_PROJECT_mavenPublishUser: ${{ github.actor }}
          ORG_GRADLE_PROJECT_mavenPublishPassword: ${{ secrets.GITHUB_TOKEN }}
