name: Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'

      - uses: gradle/actions/setup-gradle@v4 # v4.0.0

      - run: ./gradlew check

      - name: Create Changelog and Tag
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
          preset: 'conventionalcommits'
          output-file: 'docs/CHANGELOG.md'
          skip-version-file: 'true'

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
