name: Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  check:
    uses: ./.github/workflows/check.yml

  release:
    needs:
      - check
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Create Changelog and Tag
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ''
          preset: 'conventionalcommits'
          output-file: 'docs/CHANGELOG.md'
          skip-version-file: true
          skip-on-empty: false

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          make_latest: 'true'
